name: Release Plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Download Deps
        run: go mod download
      - name: Build Plugin
        run: go build -buildmode=plugin plugin/plugin.go
      - name: Upload Plugin
        uses: softprops/action-gh-release@v2
        with:
          files: plugin.so
          
