name: Tag and Release Plugin

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag-n-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump and push tag
        id: tag-merge
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Download Deps
        run: go mod download
      - name: Build Plugin
        run: go build -buildmode=plugin plugin/plugin.go
      - name: Upload Plugin
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag-merge.outputs.new_tag }}
          files: plugin.so
